[package]
name = "pfv_webgl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
speedy2d = "2.0.0"
log = "0.4.6"
wasm-logger = "0.2.0"
